AllCops:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 200

Lint/NestedMethodDefinition:
  Enabled: false

Lint/RescueException:
  Exclude:
    - 'lib/dining_philosophers/v4/lib/actor.rb'

Style/GuardClause:
  Exclude:
    - '*.gemspec'

Style/AndOr:
  Enabled: false

Documentation:
  Enabled: false

CaseIndentation:
  Enabled: false
